- index.js
> fix(indexjs) edit layer.draw example's parameter's order

- demo/buildings.html
解决 extrude building example 中点击事件的响应问题
> fix extrude building example's click event problem

- demo/bar.html
- demo/buildings-VertexColors.html
- demo/custom-circle.html
- index.js
- src/Bar.js
- src/BaseObject.js
- src/ExtrudePolygon.js
ExtrudePolygon Bar support animateShow
issue54
> ExtrudePolygon Bar support animateShow

- demo/custom-fatline.html
- demo/js/geoutil.js
- index.js
Layer identification can be implemented by baseobject
Baseobject can have its own identity method, and identity for special mesh can have its own implementation, such as fatline
> baseobject support custom identify

- index.js
> delete trailing spaces

- demo/index.html
- demo/spotlight.html
for https://github.com/maptalks/maptalks.three/issues/13
> spotlight example

- demo/index.html
- demo/vectortilelayer-wfs.html
for https://github.com/maptalks/maptalks.three/issues/11
> wfs example

- demo/custom-electricShield.html
- demo/custom-ringEffect.html
- demo/index.html
> ElectricShield

- demo/index.html
- demo/vectortilelayer-terrain.html
- index.js
- src/ExtrudeLines.js
- src/ExtrudePolygons.js
- src/TerrainVectorTileLayer.js
- src/util/MergeGeometryUtil.js
- src/worker/MeshActor.js
- src/worker/index.js
> ExtrudeLines support worker

- src/index.ts
- types/maptalks/index.d.ts
> Compatible with map getGLRes fix #327

- src/ExtrudeLines.ts
- src/ExtrudePolygons.ts
- src/index.ts
- src/util/MergeGeometryUtil.ts
- types/maptalks/index.d.ts
> Optimize memory usage about ExtrudePolygons and ExtrudeLines

- src/ExtrudePolygons.ts
- src/util/ExtrudeUtil.ts
- src/util/GeoJSONUtil.ts
- src/util/index.ts
- src/worker/MeshActor.ts
geojson的中心点计算改为重心，
优化 ExtrudePolygons的初始化性能
> optimization Extrupolygons init performance

- src/index.ts
> delete map mouse cursor

- src/Bar.ts
- src/BaseObject.ts
- src/Box.ts
- src/ExtrudeLine.ts
- src/ExtrudeLineTrail.ts
- src/ExtrudePolygon.ts
- src/type/BaseOption.ts
> BaseObject support setHeight

- demo/altitudetest.html
- src/Bar.ts
- src/Bars.ts
- src/BaseObject.ts
- src/Box.ts
- src/Boxs.ts
- src/ExtrudeLine.ts
- src/ExtrudeLineTrail.ts
- src/ExtrudeLines.ts
- src/ExtrudePolygon.ts
- src/ExtrudePolygons.ts
- src/FatLine.ts
- src/FatLines.ts
- src/HeatMap.ts
- src/Line.ts
- src/Lines.ts
- src/Model.ts
- src/Point.ts
- src/Points.ts
- src/Terrain.ts
- src/index.ts
- src/util/ExtrudeUtil.ts
- src/util/IdentifyUtil.ts
- src/util/index.ts
- src/worker/MeshActor.ts
- types/maptalks/index.d.ts
[adapt for map.altitudeToPoint](https://github.com/maptalks/maptalks.js/commit/7ad54b9b15c9fca992af3035067a31e3d98d757d)
> adapt for map.altitudeToPoint

- src/index.ts
> fix three camera.projectionMatrixInverse undefined error

- demo/groupglbloom.html
- demo/index.html
- demo/meshlayers.html
- src/BaseObject.ts
- src/index.ts
- src/type/BaseOption.ts
> adapt for groupgllayer bloom

- src/index.ts
> infowindow support autoOpenOn

- src/index.ts
- types/maptalks/index.d.ts
> Baseobject events support no propagation

- src/index.ts
> fix Multi ThreeLayer Event system does not work properly

- src/index.ts
> fix fire click events when map draging

- src/index.ts
> fix raycaster.layers undefined when Low version threejs

- src/index.ts
> simulation mouse click on mobile device

- src/BaseObject.ts
- src/index.ts
>  close uicomponent when BaseObject hide/remove

- src/BaseObjectTaskManager.ts
- src/ExtrudeLineTrail.ts
- src/util/GeoUtil.ts
- src/util/LineUtil.ts
> ExtrudeLineTrail support worker

- src/index.ts
> fix model not show when groupgl open bloom effect

- src/GPUPick.ts
> fix gpupick not work when groupgl open bloom

- src/index.ts
> fix resizeCanvas typo

- src/index.ts
> optimization bloom render frame performance

- demo/accesstoken.js
- demo/custom-geotiffplane.html
- demo/custom-imageplane.html
- demo/custom-rgbimage-terrain-landscape.html
- demo/custom-rgbimage-terrain-mapbox.html
- demo/custom-rgbimage-terrain.html
- demo/js/accesstoken.js
- demo/js/tilebelt.js
- demo/terrain.html
- demo/vectortilelayer-mvt.html
- demo/vectortilelayer-terrain.html
- src/Terrain.ts
- src/index.ts
> Terrain support updateData

- src/util/ThreeAdaptUtil.ts
const vertexColors = THREE?.['VertexColors'] ?? false
> Charles leocc patch vertex colors

- src/BaseObject.ts
- src/GPUPick.ts
- src/index.ts
- src/type/BaseOption.ts
> fix gpupick when map devicePixelRatio!==window.devicePixelRatio

- src/ExtrudeLineTrail.ts
> fix ExtrudeLineTrail animtion index overflow chunkLines.length

- demo/animation.html
> update gltf model example

- package.json
- src/util/ThreeAdaptUtil.ts
> fix THREE.VertexColors compatibility

- package.json
- rollup.config.js
- src/util/BarUtil.ts
- src/util/MergeGeometryUtil.ts
- src/util/ThreeAdaptUtil.ts
> adapt three 154 remove BoxBufferGeometry

- package.json
- src/index.ts
> adapt map new geometryevent

- src/BaseObject.ts
> tooltip postion Should be consistent with the core library

- src/index.ts
> adapt threelayer events when threelayer addto groupgllayer

- src/HeatMap.ts
> toHeatMap auto buffer canvas size

- src/BaseObjectTaskManager.ts
> fix BaseObject not find layer when worker Processing completed

- src/Model.ts
- src/index.ts
- types/maptalks/index.d.ts
> fix infowindow Repeat display

- demo/animation.html
- package-lock.json
- package.json
- src/Terrain.ts
- src/type/BaseOption.ts
> Terrain fire dataload/textureload etc events

- demo/index.html
- demo/layer-add-remove.html
- src/index.ts
> auto add meshes when layer Add to map again

- src/ExtrudeLineTrail.ts
- src/worker/MeshActor.ts
> fix ExtrudeLineTrail error when map spatialReference is not EPSGE3857

- src/BaseObject.ts
- src/FatLine.ts
- src/FatLines.ts
> fix fatline material resolution not update when map resize

- src/ExtrudeLine.ts
- src/ExtrudeLineTrail.ts
- src/ExtrudeLines.ts
- src/type/BaseOption.ts
- src/util/LineUtil.ts
- src/worker/MeshActor.ts
- src/worker/index.js
> ExtrudeLine support options.pathUV
